// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf37wrWMhO7D6lP0YZGj_EKs7qJWf5oZM',
    appId: '1:245400489251:web:b8f14f37ed5c9e7fc75096',
    messagingSenderId: '245400489251',
    projectId: 'bya-db',
    authDomain: 'bya-db.firebaseapp.com',
    storageBucket: 'bya-db.firebasestorage.app',
    measurementId: 'G-424T34N3Z2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvv_H3xfYzkVVjgX4hydAAMSSUx1oNNDw',
    appId: '1:245400489251:android:a0e79662ffeabaedc75096',
    messagingSenderId: '245400489251',
    projectId: 'bya-db',
    storageBucket: 'bya-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDleJDJahcJwUMKYNOLoHv13NPyRHRc6Ho',
    appId: '1:245400489251:ios:37d2b13f5e709437c75096',
    messagingSenderId: '245400489251',
    projectId: 'bya-db',
    storageBucket: 'bya-db.firebasestorage.app',
    iosBundleId: 'com.example.bya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDleJDJahcJwUMKYNOLoHv13NPyRHRc6Ho',
    appId: '1:245400489251:ios:37d2b13f5e709437c75096',
    messagingSenderId: '245400489251',
    projectId: 'bya-db',
    storageBucket: 'bya-db.firebasestorage.app',
    iosBundleId: 'com.example.bya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDf37wrWMhO7D6lP0YZGj_EKs7qJWf5oZM',
    appId: '1:245400489251:web:c8248730e374d689c75096',
    messagingSenderId: '245400489251',
    projectId: 'bya-db',
    authDomain: 'bya-db.firebaseapp.com',
    storageBucket: 'bya-db.firebasestorage.app',
    measurementId: 'G-STP9EB8HNM',
  );
}
